<div class="container main-container">
    <div class="row">
        <div class="col-md-12">
            <h1>Privacy Policy</h1>
            <hr />
            <p style='text-align:justify'>By accessing this application, the user hereby consents to abide by this privacy policy:</p>
            <ul>
                <li>The application shall collect various information and data from the user, from time to time. Such information shall include, but shall not be restricted to, the name, address, telephone number, fax number, email address, mode of payment, etc. The application shall be authorized to utilize any or all the information provided by the user for the purposes of processing the requests of the user, as the case maybe, as provided on the application.</li>
                <li>We endeavor and are committed to protecting any information and/or data that is provided by the user on the application. The application does not share or disclose any information of the user obtained through the application to any third parties, save and except for the services availed. The application shall not disclose any information of the user collected on this application to any third party without the prior consent of the user, save and except as required under the laws of India as applicable from time to time.</li>
                <li>The application may however utilize the information to analyze trends, administer the application, gather broad demographic information of aggregate use, etc. However, such information shall not include personally identifiable information of the user. Such information shall also not be shared with third parties and shall be used internally on a need-to-know basis.</li>
                <li>We shall not sell, share or rent your personal information to any third party or use your email address for unsolicited emails. Any emails sent by the application will only be in connection with the provision of the agreed services and in relation to any developments associated with the cause or in relation to the business of the Software.</li>
                <li>We adopt reasonable security methods and precautionary measures to prevent unauthorised access and to protect the information of the user available with us. We constantly review our systems and data to ensure the best possible service to the user. In the event of any unauthorized access of any personal data or information of the user, we undertake to initiate necessary action as per applicable Indian laws. Notwithstanding the aforesaid, given the penetrable nature of the security system we do not accept any liability regarding or guarantee relating to the security of the data/ information of the user. All information and data provided to us may be intercepted during transmission and hence the application or its affiliates and/or it directors, employees and/or agents assumes no liability with respect to any personal information and bank related information and transactions. Like most interactive application, the information of the user, is not limited to data provided on the application and is also stored in the mobile of the user. The application shall not be responsible for any loss or damaged caused to the user due to the information and data contained in their mobile.</li>
                <li>The user may not use any data of this application without our prior written consent. If you do use data of this application or any part thereof, you do so at your own risk. The application shall not accept any responsibility for any loss or damage in whatever manner, however caused, resulting from your disclosure to such third parties of personal information. The application undertakes no responsibility or liability to monitor or control the privacy practices of such third party Softwares or any other third party Software, including the content provided on such third party Softwares. User are requested to review the terms and conditions and privacy policies adopted by such third party Softwares to understand how they collect and use information.</li>
                <li>Notwithstanding anything mentioned herein, the application shall release any user related information to any government authority or under order by any statutory, administrative or judicial authority as applicable.</li>
                <li>As our constant endeavor to make our privacy policy more robust and advantageous to protect the information of our user we will periodically upgrade our privacy policy and the same shall supersede the earlier versions of the said privacy policy. We, therefore, request you to read this document each time you access the application to ensure that it still meets your approval.</li>
            </ul>
            <br />
        </div>
    </div>
</div>